/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rosangela' at '16/10/16 14:35' with Gradle 3.1
 *
 * @author Rosangela, @date 16/10/16 14:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
